test

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -1,12 +1,19 @@
 #!/bin/sh
-# Part 1
-stagedFiles=$(git diff --staged --name-only)
-# Part 2
-echo "Running spotlessApply. Formatting code..."
-./gradlew spotlessApply --daemon
-# Part 3
-for file in $stagedFiles; do
-  if test -f "$file"; then
-    git add $file
-  fi
-done
+# From gist at https://gist.github.com/chadmaughan/5889802
+
+echo '[git hook] executing gradle spotlessCheck before commit'
+
+# stash any unstaged changes
+git stash -q --keep-index
+
+# run the spotlessCheck with the gradle wrapper
+./gradlew spotlessCheck --daemon
+
+# store the last exit code in a variable
+RESULT=$?
+
+# unstash the unstashed changes
+git stash pop -q
+
+# return the './gradlew spotlessCheck' exit code
+exit $RESULT
